=== OrcaBus/service-sequence-run-manager/docs/events/SequenceRunSampleSheetUpdate/SequenceRunSampleSheetUpdate.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://raw.githubusercontent.com/umccr/orcabus/main/docs/schemas/events/sequencerunmanager/SequenceRunSampleSheetUpdate.schema.json",
  "description": "EventBridge custom event schema for orcabus.sequencerunmanager@SequenceRunSampleSheetUpdate",
  "title": "AWSEvent",
  "definitions": {
    "SequenceRunSampleSheetUpdate": {
      "type": "object",
      "required": ["instrumentRunId", "timeStamp", "sampleSheetName", "samplesheetBase64gz"],
      "properties": {
        "id": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "instrumentRunId": {
          "type": "string"
        },
        "sequenceRunId": {
          "type": "string"
        },
        "timeStamp": {
          "type": "string",
          "format": "date-time"
        },
        "sampleSheetName": {
          "type": "string"
        },
        "samplesheetBase64gz": {
          "type": "string"
        },
        "comment": {
          "$ref": "#/definitions/Comment"
        }
      }
    },
    "Comment": {
      "type": "object",
      "required": ["comment", "createdBy"],
      "properties": {
        "comment": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "source": {
      "type": "string"
    },
    "time": {
      "format": "date-time",
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "account": {
      "type": "string"
    },
    "detail-type": {
      "type": "string"
    },
    "detail": {
      "$ref": "#/definitions/SequenceRunSampleSheetUpdate"
    }
  },
  "required": ["detail", "detail-type", "source"]
}

=== OrcaBus/service-sequence-run-manager/docs/events/SequenceRunSampleSheetUpdate/examples/SRSSU__new_sequence_run.json
{
  "version": "0",
  "id": "12345678-90ab-cdef-1234-567890abcdef",
  "detail-type": "SequenceRunSampleSheetUpdate",
  "source": "anything except orcabus.sequencerunmanager e.g. orcabus.manual",
  "account": "000000000000",
  "time": "2025-03-01T00:00:00Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "instrumentRunId": "123456_A7890_1234_ABCDEFGH",
    "timeStamp": "2025-03-01T00:00:00.000000Z",
    "sampleSheetName": "sampleSheet_v2.csv",
    "samplesheetBase64gz": "base64_encoded_gzipped_samplesheet_csv"
  }
}

=== OrcaBus/service-sequence-run-manager/docs/events/SequenceRunSampleSheetUpdate/examples/SRSSU.json
{
  "version": "0",
  "id": "12345678-90ab-cdef-1234-567890abcdef",
  "detail-type": "SequenceRunSampleSheetUpdate",
  "source": "anything except orcabus.sequencerunmanager e.g. orcabus.manual",
  "account": "000000000000",
  "time": "2025-03-01T00:00:00Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "id": "6b039445b1582ae61dad7b32a0550f20",
    "version": "1.0.0",
    "instrumentRunId": "123456_A7890_1234_ABCDEFGH",
    "sequenceRunId": "r.1234567890abcdefghijklmn",
    "timeStamp": "2025-03-01T00:00:00.000000Z",
    "sampleSheetName": "sampleSheet_v2.csv",
    "samplesheetBase64gz": "base64_encoded_gzipped_samplesheet_csv",
    "comment": {
      "comment": "Corrected the index of library L2000001",
      "createdBy": "jane.doe@example.org"
    }
  }
}
