=== OrcaBus/service-sequence-run-manager/docs/events/SequenceRunStateChange/SequenceRunStateChange.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://raw.githubusercontent.com/umccr/orcabus/main/docs/schemas/events/sequencerunmanager/SequenceRunStateChange.schema.json",
  "description": "EventBridge custom event schema for orcabus.sequencerunmanager@SequenceRunStateChange",
  "title": "AWSEvent",
  "definitions": {
    "SequenceRunStateChange": {
      "type": "object",
      "required": [
        "id",
        "version",
        "orcabusId",
        "instrumentRunId",
        "runVolumeName",
        "runFolderPath",
        "runDataUri",
        "sampleSheetName",
        "startTime",
        "status"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "orcabusId": {
          "type": "string"
        },
        "instrumentRunId": {
          "type": "string"
        },
        "runVolumeName": {
          "type": "string"
        },
        "runFolderPath": {
          "type": "string"
        },
        "runDataUri": {
          "type": "string"
        },
        "sampleSheetName": {
          "type": ["string", "null"]
        },
        "startTime": {
          "type": "string",
          "format": "date-time"
        },
        "endTime": {
          "type": ["string", "null"],
          "format": "date-time"
        },
        "status": {
          "type": "string"
        },
        "stateCreatedBy": {
          "type": "string"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "source": {
      "type": "string"
    },
    "time": {
      "format": "date-time",
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "account": {
      "type": "string"
    },
    "detail-type": {
      "type": "string"
    },
    "detail": {
      "$ref": "#/definitions/SequenceRunStateChange"
    }
  },
  "required": ["detail", "detail-type", "source"]
}

=== OrcaBus/service-sequence-run-manager/docs/events/SequenceRunStateChange/examples/SRSC__started__null.json
{
  "version": "0",
  "id": "fffFfffe-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "SequenceRunStateChange",
  "source": "orcabus.sequencerunmanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "id": "8e50e37cf756387613e0f19675b6ba01",
    "version": "1.1.0",
    "orcabusId": "seq.0123456ABCDEFG",
    "instrumentRunId": "540424_A01001_0193_BBBBBBDRX5",
    "runVolumeName": "bssh.abcdefgh1234567899fa94fe79523959",
    "runFolderPath": "/Runs/540424_A01001_0193_BBBBBBDRX5_r.88888888ASU26EYuyeJHew",
    "runDataUri": "gds://bssh.abcdefgh1234567899fa94fe79523959/Runs/540424_A01001_0193_BBBBBBDRX5_r.88888888ASU26EYuyeJHew",
    "sampleSheetName": null,
    "startTime": "2024-04-27T03:45:02.113245Z",
    "endTime": null,
    "status": "STARTED"
  }
}

=== OrcaBus/service-sequence-run-manager/docs/events/SequenceRunStateChange/examples/SRSC__resolved.json
{
  "version": "0",
  "id": "fffFfffe-5b36-40c2-f7dc-804ca6270cd6",
  "detail-type": "SequenceRunStateChange",
  "source": "orcabus.sequencerunmanager",
  "account": "123456789012",
  "time": "2024-05-01T09:25:44Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "id": "52d5dcf7fa84818a58967668005c1411",
    "version": "1.1.0",
    "orcabusId": "seq.0123456ABCDEFG",
    "instrumentRunId": "540424_A01001_0193_BBBBBBDRX5",
    "runVolumeName": "bssh.abcdefgh1234567899fa94fe79523959",
    "runFolderPath": "/Runs/540424_A01001_0193_BBBBBBDRX5_r.88888888ASU26EYuyeJHew",
    "runDataUri": "gds://bssh.abcdefgh1234567899fa94fe79523959/Runs/540424_A01001_0193_BBBBBBDRX5_r.88888888ASU26EYuyeJHew",
    "sampleSheetName": "SampleSheet.csv",
    "startTime": "2024-04-27T03:45:02.113245Z",
    "endTime": "2024-04-27T09:12:44.113245Z",
    "status": "RESOLVED",
    "stateCreatedBy": "jane.doe@example.org"
  }
}
