=== OrcaBus/service-sequence-run-manager/docs/events/SequenceRunLibraryLinkingChange/SequenceRunLibraryLinkingChange.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://raw.githubusercontent.com/umccr/orcabus/main/docs/schemas/events/sequencerunmanager/SequenceRunLibraryLinkingChange.schema.json",
  "description": "EventBridge custom event schema for orcabus.sequencerunmanager@SequenceRunLibraryLinkingChange",
  "title": "AWSEvent",
  "definitions": {
    "SequenceRunLibraryLinkingChange": {
      "type": "object",
      "required": [
        "id",
        "version",
        "instrumentRunId",
        "sequenceRunId",
        "timeStamp",
        "linkedLibraries"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "instrumentRunId": {
          "type": "string"
        },
        "sequenceRunId": {
          "type": "string"
        },
        "timeStamp": {
          "type": "string",
          "format": "date-time"
        },
        "linkedLibraries": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "source": {
      "type": "string"
    },
    "time": {
      "format": "date-time",
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "account": {
      "type": "string"
    },
    "detail-type": {
      "type": "string"
    },
    "detail": {
      "$ref": "#/definitions/SequenceRunLibraryLinkingChange"
    }
  },
  "required": ["detail", "detail-type", "source"]
}

=== OrcaBus/service-sequence-run-manager/docs/events/SequenceRunLibraryLinkingChange/examples/SRLLC.json
{
  "version": "0",
  "id": "12345678-90ab-cdef-1234-567890abcdef",
  "detail-type": "SequenceRunLibraryLinkingChange",
  "source": "orcabus.sequencerunmanager",
  "account": "000000000000",
  "time": "2024-04-27T03:45:02.113245Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "id": "ad0abebb56dfdaad68886e71cca84a3c",
    "version": "1.1.0",
    "instrumentRunId": "123456_A7890_1234_ABCDEFGH",
    "sequenceRunId": "r.1234567890abcdefghijklmn",
    "timeStamp": "2025-03-01T00:00:00.123456Z",
    "linkedLibraries": ["L2000000", "L2000001", "L2000002"]
  }
}
