=== OrcaBus/service-sequence-run-manager/docs/events/SequenceRunLibraryLinkingUpdate/SequenceRunLibraryLinkingUpdate.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://raw.githubusercontent.com/umccr/orcabus/main/docs/schemas/events/sequencerunmanager/SequenceRunLibraryLinkingUpdate.schema.json",
  "description": "EventBridge custom event schema for orcabus.sequencerunmanager@SequenceRunLibraryLinkingUpdate",
  "title": "AWSEvent",
  "definitions": {
    "SequenceRunLibraryLinkingUpdate": {
      "type": "object",
      "required": ["instrumentRunId", "sequenceRunId", "timeStamp", "linkedLibraries"],
      "properties": {
        "id": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "instrumentRunId": {
          "type": "string"
        },
        "sequenceRunId": {
          "type": "string"
        },
        "timeStamp": {
          "type": "string",
          "format": "date-time"
        },
        "linkedLibraries": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "region": {
      "type": "string"
    },
    "resources": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "source": {
      "type": "string"
    },
    "time": {
      "format": "date-time",
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "account": {
      "type": "string"
    },
    "detail-type": {
      "type": "string"
    },
    "detail": {
      "$ref": "#/definitions/SequenceRunLibraryLinkingUpdate"
    }
  },
  "required": ["detail", "detail-type", "source"]
}

=== OrcaBus/service-sequence-run-manager/docs/events/SequenceRunLibraryLinkingUpdate/examples/SRLLU.json
{
  "version": "0",
  "id": "12345678-90ab-cdef-1234-567890abcdef",
  "detail-type": "SequenceRunLibraryLinkingUpdate",
  "source": "anything except orcabus.sequencerunmanager e.g. orcabus.manual",
  "account": "000000000000",
  "time": "2025-03-01T00:00:00Z",
  "region": "ap-southeast-2",
  "resources": [],
  "detail": {
    "id": "5ec963c26aa70134cc5ee3c875feea56",
    "version": "1.0.0",
    "instrumentRunId": "123456_A7890_1234_ABCDEFGH",
    "sequenceRunId": "r.1234567890abcdefghijklmn",
    "timeStamp": "2025-03-01T00:00:00.000000Z",
    "linkedLibraries": ["L2000000", "L2000001", "L2000002", "L2000003"]
  }
}
